services:
  - type: web
    name: storage-hqs-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'webapp:create_app()'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_ADMIN_USERNAME
        value: STAN_ADM
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DATA_DIR
        value: /var/data
